"""add HR + AP Agent tables

Hand-written (not autogenerated) migration that adds:
  • HR: hr_employees, hr_leave_requests, hr_payroll_runs, hr_payslips
  • AP Agent: ap_invoices, ap_line_items

Revision ID: 1a8f7d2b4e5c
Revises: 2b92f970a8f9
Create Date: 2026-04-17
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a8f7d2b4e5c"
down_revision: Union[str, Sequence[str], None] = "2b92f970a8f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema — create HR + AP tables."""

    # ── hr_employees ────────────────────────────────────────
    op.create_table(
        "hr_employees",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("tenant_id", sa.String(length=36), nullable=True),
        sa.Column(
            "user_id",
            sa.String(length=36),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("employee_number", sa.String(length=32), nullable=False),
        sa.Column("name_ar", sa.String(length=200), nullable=False),
        sa.Column("name_en", sa.String(length=200), nullable=True),
        sa.Column("national_id", sa.String(length=20), nullable=True),
        sa.Column("iqama_number", sa.String(length=20), nullable=True),
        sa.Column("emirates_id", sa.String(length=20), nullable=True),
        sa.Column("nationality", sa.String(length=3), nullable=True),
        sa.Column("department", sa.String(length=100), nullable=True),
        sa.Column("job_title", sa.String(length=120), nullable=True),
        sa.Column("hire_date", sa.Date(), nullable=False),
        sa.Column("termination_date", sa.Date(), nullable=True),
        sa.Column("basic_salary", sa.Numeric(18, 2), nullable=False),
        sa.Column("housing_allowance", sa.Numeric(18, 2), nullable=False),
        sa.Column("transport_allowance", sa.Numeric(18, 2), nullable=False),
        sa.Column("other_allowances", sa.Numeric(18, 2), nullable=False),
        sa.Column("bank_iban", sa.String(length=40), nullable=True),
        sa.Column("bank_name", sa.String(length=120), nullable=True),
        sa.Column("gosi_number", sa.String(length=32), nullable=True),
        sa.Column("gosi_applicable", sa.Boolean(), nullable=False),
        sa.Column("gosi_employee_rate", sa.Numeric(5, 4), nullable=False),
        sa.Column("gosi_employer_rate", sa.Numeric(5, 4), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("tenant_id", "employee_number", name="uq_hr_emp_tenant_num"),
    )
    op.create_index("ix_hr_employees_tenant_id", "hr_employees", ["tenant_id"])
    op.create_index("ix_hr_employees_employee_number", "hr_employees", ["employee_number"])
    op.create_index("ix_hr_employees_national_id", "hr_employees", ["national_id"])
    op.create_index("ix_hr_employees_iqama_number", "hr_employees", ["iqama_number"])
    op.create_index("ix_hr_employees_emirates_id", "hr_employees", ["emirates_id"])
    op.create_index("ix_hr_employees_status", "hr_employees", ["status"])

    # ── hr_leave_requests ───────────────────────────────────
    op.create_table(
        "hr_leave_requests",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("tenant_id", sa.String(length=36), nullable=True),
        sa.Column(
            "employee_id",
            sa.String(length=36),
            sa.ForeignKey("hr_employees.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("leave_type", sa.String(length=20), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("days", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("approved_by", sa.String(length=36), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_hr_leave_requests_tenant_id", "hr_leave_requests", ["tenant_id"])
    op.create_index("ix_hr_leave_requests_employee_id", "hr_leave_requests", ["employee_id"])
    op.create_index("ix_hr_leave_requests_status", "hr_leave_requests", ["status"])

    # ── hr_payroll_runs ─────────────────────────────────────
    op.create_table(
        "hr_payroll_runs",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("tenant_id", sa.String(length=36), nullable=True),
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("total_gross", sa.Numeric(18, 2), nullable=False),
        sa.Column("total_deductions", sa.Numeric(18, 2), nullable=False),
        sa.Column("total_net", sa.Numeric(18, 2), nullable=False),
        sa.Column("employee_count", sa.Integer(), nullable=False),
        sa.Column("wps_reference", sa.String(length=64), nullable=True),
        sa.Column("wps_file_url", sa.String(length=500), nullable=True),
        sa.Column("approved_by", sa.String(length=36), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("tenant_id", "period", name="uq_hr_payroll_tenant_period"),
    )
    op.create_index("ix_hr_payroll_runs_tenant_id", "hr_payroll_runs", ["tenant_id"])
    op.create_index("ix_hr_payroll_runs_period", "hr_payroll_runs", ["period"])
    op.create_index("ix_hr_payroll_runs_status", "hr_payroll_runs", ["status"])

    # ── hr_payslips ─────────────────────────────────────────
    op.create_table(
        "hr_payslips",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("tenant_id", sa.String(length=36), nullable=True),
        sa.Column(
            "payroll_run_id",
            sa.String(length=36),
            sa.ForeignKey("hr_payroll_runs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "employee_id",
            sa.String(length=36),
            sa.ForeignKey("hr_employees.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("basic_salary", sa.Numeric(18, 2), nullable=False),
        sa.Column("housing_allowance", sa.Numeric(18, 2), nullable=False),
        sa.Column("transport_allowance", sa.Numeric(18, 2), nullable=False),
        sa.Column("other_allowances", sa.Numeric(18, 2), nullable=False),
        sa.Column("gosi_deduction", sa.Numeric(18, 2), nullable=False),
        sa.Column("absence_deduction", sa.Numeric(18, 2), nullable=False),
        sa.Column("other_deductions", sa.Numeric(18, 2), nullable=False),
        sa.Column("gross", sa.Numeric(18, 2), nullable=False),
        sa.Column("net", sa.Numeric(18, 2), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=True),
        sa.Column("wps_reference", sa.String(length=64), nullable=True),
        sa.Column("pdf_url", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("payroll_run_id", "employee_id", name="uq_hr_payslip_run_emp"),
    )
    op.create_index("ix_hr_payslips_tenant_id", "hr_payslips", ["tenant_id"])

    # ── ap_invoices ─────────────────────────────────────────
    op.create_table(
        "ap_invoices",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("tenant_id", sa.String(length=36), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("source_ref", sa.String(length=200), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_file_url", sa.String(length=500), nullable=True),
        sa.Column("vendor_id", sa.String(length=36), nullable=True),
        sa.Column("vendor_name", sa.String(length=200), nullable=True),
        sa.Column("invoice_number", sa.String(length=64), nullable=True),
        sa.Column("invoice_date", sa.Date(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("subtotal", sa.Numeric(18, 2), nullable=True),
        sa.Column("vat_amount", sa.Numeric(18, 2), nullable=True),
        sa.Column("total", sa.Numeric(18, 2), nullable=True),
        sa.Column("vendor_iban", sa.String(length=40), nullable=True),
        sa.Column("ocr_confidence", sa.Numeric(5, 4), nullable=True),
        sa.Column("matched_po_id", sa.String(length=36), nullable=True),
        sa.Column("matched_receipt_id", sa.String(length=36), nullable=True),
        sa.Column("match_variance", sa.Numeric(18, 2), nullable=True),
        sa.Column("suggested_account_id", sa.String(length=36), nullable=True),
        sa.Column("coding_confidence", sa.Numeric(5, 4), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("approval_policy", sa.String(length=32), nullable=True),
        sa.Column("approved_by", sa.String(length=36), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scheduled_payment_date", sa.Date(), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payment_reference", sa.String(length=64), nullable=True),
        sa.Column("exceptions", sa.JSON(), nullable=True),
        sa.Column("pipeline_log", sa.JSON(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_ap_invoices_tenant_id", "ap_invoices", ["tenant_id"])
    op.create_index("ix_ap_invoices_vendor_id", "ap_invoices", ["vendor_id"])
    op.create_index("ix_ap_invoices_matched_po_id", "ap_invoices", ["matched_po_id"])
    op.create_index("ix_ap_invoices_matched_receipt_id", "ap_invoices", ["matched_receipt_id"])
    op.create_index("ix_ap_invoices_status", "ap_invoices", ["status"])

    # ── ap_line_items ───────────────────────────────────────
    op.create_table(
        "ap_line_items",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column(
            "invoice_id",
            sa.String(length=36),
            sa.ForeignKey("ap_invoices.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("quantity", sa.Numeric(18, 4), nullable=False),
        sa.Column("unit_price", sa.Numeric(18, 2), nullable=False),
        sa.Column("vat_rate", sa.Numeric(5, 2), nullable=False),
        sa.Column("line_net", sa.Numeric(18, 2), nullable=False),
        sa.Column("line_vat", sa.Numeric(18, 2), nullable=False),
        sa.Column("line_total", sa.Numeric(18, 2), nullable=False),
        sa.Column("matched_po_line_id", sa.String(length=36), nullable=True),
        sa.Column("suggested_account_id", sa.String(length=36), nullable=True),
    )
    op.create_index("ix_ap_line_items_invoice_id", "ap_line_items", ["invoice_id"])


def downgrade() -> None:
    """Downgrade schema — drop in reverse dependency order."""
    op.drop_index("ix_ap_line_items_invoice_id", table_name="ap_line_items")
    op.drop_table("ap_line_items")

    op.drop_index("ix_ap_invoices_status", table_name="ap_invoices")
    op.drop_index("ix_ap_invoices_matched_receipt_id", table_name="ap_invoices")
    op.drop_index("ix_ap_invoices_matched_po_id", table_name="ap_invoices")
    op.drop_index("ix_ap_invoices_vendor_id", table_name="ap_invoices")
    op.drop_index("ix_ap_invoices_tenant_id", table_name="ap_invoices")
    op.drop_table("ap_invoices")

    op.drop_index("ix_hr_payslips_tenant_id", table_name="hr_payslips")
    op.drop_table("hr_payslips")

    op.drop_index("ix_hr_payroll_runs_status", table_name="hr_payroll_runs")
    op.drop_index("ix_hr_payroll_runs_period", table_name="hr_payroll_runs")
    op.drop_index("ix_hr_payroll_runs_tenant_id", table_name="hr_payroll_runs")
    op.drop_table("hr_payroll_runs")

    op.drop_index("ix_hr_leave_requests_status", table_name="hr_leave_requests")
    op.drop_index("ix_hr_leave_requests_employee_id", table_name="hr_leave_requests")
    op.drop_index("ix_hr_leave_requests_tenant_id", table_name="hr_leave_requests")
    op.drop_table("hr_leave_requests")

    op.drop_index("ix_hr_employees_status", table_name="hr_employees")
    op.drop_index("ix_hr_employees_emirates_id", table_name="hr_employees")
    op.drop_index("ix_hr_employees_iqama_number", table_name="hr_employees")
    op.drop_index("ix_hr_employees_national_id", table_name="hr_employees")
    op.drop_index("ix_hr_employees_employee_number", table_name="hr_employees")
    op.drop_index("ix_hr_employees_tenant_id", table_name="hr_employees")
    op.drop_table("hr_employees")
