"""initial_schema_74_models

Revision ID: 2b92f970a8f9
Revises: 
Create Date: 2026-04-11 08:56:49.168436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b92f970a8f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_audit_log',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=12), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('field_changed', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_audit_log_entity_id'), 'knowledge_audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_knowledge_audit_log_entity_type'), 'knowledge_audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_knowledge_audit_log_timestamp'), 'knowledge_audit_log', ['timestamp'], unique=False)
    op.create_table('knowledge_authorities',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('jurisdiction', sa.String(length=10), nullable=True),
    sa.Column('domain_scope', sa.JSON(), nullable=True),
    sa.Column('official_urls', sa.JSON(), nullable=True),
    sa.Column('source_priority', sa.Integer(), nullable=True),
    sa.Column('update_frequency', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_authorities_code'), 'knowledge_authorities', ['code'], unique=True)
    op.create_table('knowledge_cases',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('domain', sa.String(length=30), nullable=True),
    sa.Column('sector', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('lessons_json', sa.JSON(), nullable=True),
    sa.Column('linked_rules', sa.JSON(), nullable=True),
    sa.Column('linked_entries', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('date_recorded', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_cases_domain'), 'knowledge_cases', ['domain'], unique=False)
    op.create_index(op.f('ix_knowledge_cases_status'), 'knowledge_cases', ['status'], unique=False)
    op.create_table('knowledge_domains',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_domains_code'), 'knowledge_domains', ['code'], unique=True)
    op.create_table('knowledge_patterns',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('domain', sa.String(length=30), nullable=True),
    sa.Column('sector', sa.String(length=30), nullable=True),
    sa.Column('pattern_type', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_json', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_patterns_domain'), 'knowledge_patterns', ['domain'], unique=False)
    op.create_table('knowledge_playbooks',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=30), nullable=True),
    sa.Column('sector', sa.String(length=30), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('when_to_use', sa.Text(), nullable=True),
    sa.Column('required_inputs', sa.JSON(), nullable=True),
    sa.Column('invoked_rules', sa.JSON(), nullable=True),
    sa.Column('invoked_entries', sa.JSON(), nullable=True),
    sa.Column('steps_json', sa.JSON(), nullable=True),
    sa.Column('outputs_expected', sa.JSON(), nullable=True),
    sa.Column('risk_flags', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_playbooks_domain'), 'knowledge_playbooks', ['domain'], unique=False)
    op.create_table('knowledge_review_queue',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=12), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=True),
    sa.Column('requested_by', sa.String(length=50), nullable=True),
    sa.Column('assigned_to', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_review_queue_entity_id'), 'knowledge_review_queue', ['entity_id'], unique=False)
    op.create_index(op.f('ix_knowledge_review_queue_status'), 'knowledge_review_queue', ['status'], unique=False)
    op.create_table('knowledge_sectors',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_sector_id', sa.String(length=12), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_sector_id'], ['knowledge_sectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_sectors_code'), 'knowledge_sectors', ['code'], unique=True)
    op.create_index(op.f('ix_knowledge_sectors_parent_sector_id'), 'knowledge_sectors', ['parent_sector_id'], unique=False)
    op.create_table('knowledge_updates',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('update_type', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('authority_code', sa.String(length=20), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('impacted_domains', sa.JSON(), nullable=True),
    sa.Column('impacted_rules', sa.JSON(), nullable=True),
    sa.Column('impacted_entries', sa.JSON(), nullable=True),
    sa.Column('impacted_playbooks', sa.JSON(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('review_deadline', sa.Date(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_updates_status'), 'knowledge_updates', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_updates_update_type'), 'knowledge_updates', ['update_type'], unique=False)
    op.create_table('knowledge_sector_mappings',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('sector_code', sa.String(length=30), nullable=True),
    sa.Column('entity_type', sa.String(length=20), nullable=True),
    sa.Column('entity_id', sa.String(length=12), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sector_code'], ['knowledge_sectors.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_sector_mappings_entity_id'), 'knowledge_sector_mappings', ['entity_id'], unique=False)
    op.create_index(op.f('ix_knowledge_sector_mappings_sector_code'), 'knowledge_sector_mappings', ['sector_code'], unique=False)
    op.create_table('knowledge_sources',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('domain', sa.String(length=30), nullable=True),
    sa.Column('subdomain', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('authority_code', sa.String(length=20), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=True),
    sa.Column('legal_force', sa.String(length=30), nullable=True),
    sa.Column('official_reference', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('version_label', sa.String(length=20), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('superseded_by', sa.String(length=12), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['authority_code'], ['knowledge_authorities.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_source_domain_status', 'knowledge_sources', ['domain', 'status'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_authority_code'), 'knowledge_sources', ['authority_code'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_domain'), 'knowledge_sources', ['domain'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_source_type'), 'knowledge_sources', ['source_type'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_status'), 'knowledge_sources', ['status'], unique=False)
    op.create_table('knowledge_entries',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('source_id', sa.String(length=12), nullable=True),
    sa.Column('entry_code', sa.String(length=50), nullable=True),
    sa.Column('domain', sa.String(length=30), nullable=True),
    sa.Column('subdomain', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('structured_json', sa.JSON(), nullable=True),
    sa.Column('applicability_json', sa.JSON(), nullable=True),
    sa.Column('obligations_json', sa.JSON(), nullable=True),
    sa.Column('exceptions_json', sa.JSON(), nullable=True),
    sa.Column('impacts_json', sa.JSON(), nullable=True),
    sa.Column('linked_rules', sa.JSON(), nullable=True),
    sa.Column('linked_cases', sa.JSON(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('obligation_level', sa.String(length=20), nullable=True),
    sa.Column('review_frequency', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=True),
    sa.Column('owner_user', sa.String(length=50), nullable=True),
    sa.Column('reviewer_user', sa.String(length=50), nullable=True),
    sa.Column('approver_user', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entry_domain_status', 'knowledge_entries', ['domain', 'status'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_domain'), 'knowledge_entries', ['domain'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_entry_code'), 'knowledge_entries', ['entry_code'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_source_id'), 'knowledge_entries', ['source_id'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_status'), 'knowledge_entries', ['status'], unique=False)
    op.create_table('knowledge_rules',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('domain', sa.String(length=30), nullable=True),
    sa.Column('subdomain', sa.String(length=50), nullable=True),
    sa.Column('rule_name_ar', sa.String(length=200), nullable=False),
    sa.Column('rule_name_en', sa.String(length=200), nullable=True),
    sa.Column('rule_type', sa.String(length=30), nullable=True),
    sa.Column('scope', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('condition_json', sa.JSON(), nullable=True),
    sa.Column('action_json', sa.JSON(), nullable=True),
    sa.Column('exception_json', sa.JSON(), nullable=True),
    sa.Column('source_entry_id', sa.String(length=12), nullable=True),
    sa.Column('authority_code', sa.String(length=20), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('obligation_level', sa.String(length=20), nullable=True),
    sa.Column('confidence_weight', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_entry_id'], ['knowledge_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_rules_active'), 'knowledge_rules', ['active'], unique=False)
    op.create_index(op.f('ix_knowledge_rules_domain'), 'knowledge_rules', ['domain'], unique=False)
    op.create_index(op.f('ix_knowledge_rules_rule_code'), 'knowledge_rules', ['rule_code'], unique=True)
    op.create_index(op.f('ix_knowledge_rules_source_entry_id'), 'knowledge_rules', ['source_entry_id'], unique=False)
    op.create_table('knowledge_rule_versions',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('rule_id', sa.String(length=12), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['knowledge_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_rule_versions_rule_id'), 'knowledge_rule_versions', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_rule_versions_rule_id'), table_name='knowledge_rule_versions')
    op.drop_table('knowledge_rule_versions')
    op.drop_index(op.f('ix_knowledge_rules_source_entry_id'), table_name='knowledge_rules')
    op.drop_index(op.f('ix_knowledge_rules_rule_code'), table_name='knowledge_rules')
    op.drop_index(op.f('ix_knowledge_rules_domain'), table_name='knowledge_rules')
    op.drop_index(op.f('ix_knowledge_rules_active'), table_name='knowledge_rules')
    op.drop_table('knowledge_rules')
    op.drop_index(op.f('ix_knowledge_entries_status'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_source_id'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_entry_code'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_domain'), table_name='knowledge_entries')
    op.drop_index('idx_entry_domain_status', table_name='knowledge_entries')
    op.drop_table('knowledge_entries')
    op.drop_index(op.f('ix_knowledge_sources_status'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_source_type'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_domain'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_authority_code'), table_name='knowledge_sources')
    op.drop_index('idx_source_domain_status', table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sector_mappings_sector_code'), table_name='knowledge_sector_mappings')
    op.drop_index(op.f('ix_knowledge_sector_mappings_entity_id'), table_name='knowledge_sector_mappings')
    op.drop_table('knowledge_sector_mappings')
    op.drop_index(op.f('ix_knowledge_updates_update_type'), table_name='knowledge_updates')
    op.drop_index(op.f('ix_knowledge_updates_status'), table_name='knowledge_updates')
    op.drop_table('knowledge_updates')
    op.drop_index(op.f('ix_knowledge_sectors_parent_sector_id'), table_name='knowledge_sectors')
    op.drop_index(op.f('ix_knowledge_sectors_code'), table_name='knowledge_sectors')
    op.drop_table('knowledge_sectors')
    op.drop_index(op.f('ix_knowledge_review_queue_status'), table_name='knowledge_review_queue')
    op.drop_index(op.f('ix_knowledge_review_queue_entity_id'), table_name='knowledge_review_queue')
    op.drop_table('knowledge_review_queue')
    op.drop_index(op.f('ix_knowledge_playbooks_domain'), table_name='knowledge_playbooks')
    op.drop_table('knowledge_playbooks')
    op.drop_index(op.f('ix_knowledge_patterns_domain'), table_name='knowledge_patterns')
    op.drop_table('knowledge_patterns')
    op.drop_index(op.f('ix_knowledge_domains_code'), table_name='knowledge_domains')
    op.drop_table('knowledge_domains')
    op.drop_index(op.f('ix_knowledge_cases_status'), table_name='knowledge_cases')
    op.drop_index(op.f('ix_knowledge_cases_domain'), table_name='knowledge_cases')
    op.drop_table('knowledge_cases')
    op.drop_index(op.f('ix_knowledge_authorities_code'), table_name='knowledge_authorities')
    op.drop_table('knowledge_authorities')
    op.drop_index(op.f('ix_knowledge_audit_log_timestamp'), table_name='knowledge_audit_log')
    op.drop_index(op.f('ix_knowledge_audit_log_entity_type'), table_name='knowledge_audit_log')
    op.drop_index(op.f('ix_knowledge_audit_log_entity_id'), table_name='knowledge_audit_log')
    op.drop_table('knowledge_audit_log')
    # ### end Alembic commands ###
