"""q1_2026_infra_tables: activity_log, tenant_branding, sync_operation, zatca_submissions

Adds the four infrastructure tables that the Chatter pipeline, the
white-label config, the PWA offline queue, and the ZATCA retry queue
depend on.

Written by hand (not autogenerated) so the migration only contains
these four tables. Autogenerate wanted to recreate the entire schema
because dev DBs are bootstrapped via Base.metadata.create_all() today,
which leaves Alembic's view of "current schema" permanently empty.

Revision ID: c7f1a9b02e10
Revises: 1a8f7d2b4e5c
Create Date: 2026-04-17
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "c7f1a9b02e10"
down_revision: Union[str, Sequence[str], None] = "1a8f7d2b4e5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the four new infra tables.

    Uses checkfirst=True equivalents (explicit IF NOT EXISTS guard via
    `inspector.has_table`) so this migration is safe to re-run against
    databases that were bootstrapped by `Base.metadata.create_all()`.
    """
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if not inspector.has_table("activity_log"):
        op.create_table(
            "activity_log",
            sa.Column("id", sa.String(length=36), primary_key=True),
            sa.Column("tenant_id", sa.String(length=36), nullable=True, index=True),
            sa.Column("entity_type", sa.String(length=40), nullable=False),
            sa.Column("entity_id", sa.String(length=36), nullable=False),
            sa.Column("action", sa.String(length=40), nullable=False),
            sa.Column("user_id", sa.String(length=36), nullable=True),
            sa.Column("user_name", sa.String(length=120), nullable=True),
            sa.Column("summary", sa.Text, nullable=True),
            sa.Column("details", sa.JSON, nullable=True),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                nullable=False,
                server_default=sa.func.now(),
                index=True,
            ),
        )
        op.create_index(
            "idx_activity_entity",
            "activity_log",
            ["entity_type", "entity_id"],
        )
        op.create_index("idx_activity_created", "activity_log", ["created_at"])

    if not inspector.has_table("tenant_branding"):
        op.create_table(
            "tenant_branding",
            sa.Column("id", sa.String(length=36), primary_key=True),
            sa.Column("tenant_id", sa.String(length=36), nullable=True, index=True),
            sa.Column(
                "brand_text",
                sa.String(length=120),
                nullable=False,
                server_default="APEX",
            ),
            sa.Column(
                "primary_hex",
                sa.String(length=9),
                nullable=False,
                server_default="#D4AF37",
            ),
            sa.Column(
                "secondary_hex",
                sa.String(length=9),
                nullable=False,
                server_default="#2E75B6",
            ),
            sa.Column(
                "dark_mode",
                sa.Boolean,
                nullable=False,
                server_default=sa.true(),
            ),
            sa.Column(
                "radius_scale",
                sa.Float,
                nullable=False,
                server_default="1.0",
            ),
            sa.Column(
                "type_scale",
                sa.Float,
                nullable=False,
                server_default="1.0",
            ),
            sa.Column("logo_url", sa.String(length=500), nullable=True),
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                nullable=False,
                server_default=sa.func.now(),
            ),
        )

    if not inspector.has_table("sync_operations"):
        op.create_table(
            "sync_operations",
            sa.Column("id", sa.String(length=36), primary_key=True),
            sa.Column("tenant_id", sa.String(length=36), nullable=True, index=True),
            sa.Column("op_id", sa.String(length=64), nullable=False, unique=True, index=True),
            sa.Column("entity_type", sa.String(length=40), nullable=False, index=True),
            sa.Column("entity_id", sa.String(length=36), nullable=True, index=True),
            sa.Column("verb", sa.String(length=20), nullable=False),
            sa.Column("payload", sa.JSON, nullable=True),
            sa.Column("client_timestamp", sa.DateTime(timezone=True), nullable=False),
            sa.Column(
                "received_at",
                sa.DateTime(timezone=True),
                nullable=False,
                server_default=sa.func.now(),
                index=True,
            ),
            sa.Column(
                "status",
                sa.String(length=16),
                nullable=False,
                server_default="pending",
                index=True,
            ),
            sa.Column("result", sa.JSON, nullable=True),
            sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("user_id", sa.String(length=36), nullable=True),
        )

    if not inspector.has_table("zatca_submissions"):
        op.create_table(
            "zatca_submissions",
            sa.Column("id", sa.String(length=36), primary_key=True),
            sa.Column("tenant_id", sa.String(length=36), nullable=True, index=True),
            sa.Column("invoice_uuid", sa.String(length=36), nullable=False, index=True),
            sa.Column("invoice_number", sa.String(length=64), nullable=False, index=True),
            sa.Column("invoice_hash_b64", sa.String(length=128), nullable=False),
            sa.Column("invoice_type", sa.String(length=16), nullable=False),
            sa.Column("signed_xml", sa.Text, nullable=False),
            sa.Column(
                "status",
                sa.String(length=16),
                nullable=False,
                server_default="pending",
                index=True,
            ),
            sa.Column(
                "attempts",
                sa.Integer,
                nullable=False,
                server_default="0",
            ),
            sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True, index=True),
            sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("last_http_status", sa.Integer, nullable=True),
            sa.Column("last_error", sa.Text, nullable=True),
            sa.Column("cleared_invoice_b64", sa.Text, nullable=True),
            sa.Column("warnings", sa.JSON, nullable=True),
            sa.Column("errors", sa.JSON, nullable=True),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                nullable=False,
                server_default=sa.func.now(),
            ),
            sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        )


def downgrade() -> None:
    """Drop the four infra tables in reverse order."""
    op.drop_table("zatca_submissions")
    op.drop_table("sync_operations")
    op.drop_table("tenant_branding")
    op.drop_index("idx_activity_created", table_name="activity_log")
    op.drop_index("idx_activity_entity", table_name="activity_log")
    op.drop_table("activity_log")
