"""dashboard_widgets_layouts_cache

DASH-1, Sprint 16 — adds 3 tables for the customizable dashboard:

    dashboard_widgets        — catalog of available widgets (system + tenant)
    dashboard_layouts        — per-user / per-role / per-tenant arrangements
    dashboard_data_cache     — short-lived snapshot store for SSE replay

Hand-written rather than autogenerated because the dev SQLite DB carried
a long tail of pre-existing drift (knowledge_brain tables, reference_*,
funding_*, etc.) that polluted the autogen output. The hand-written
revision contains only the dashboard tables — diff-clean against any
fresh `create_all`-built DB.

Revision ID: h2c5e8f1a4b7
Revises: g1e2b4c9f3d8
Create Date: 2026-05-06
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# ── Identifiers ────────────────────────────────────────────


revision: str = "h2c5e8f1a4b7"
down_revision: Union[str, None] = "g1e2b4c9f3d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ── Upgrade / Downgrade ───────────────────────────────────


def upgrade() -> None:
    # Widget catalog
    op.create_table(
        "dashboard_widgets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=True),
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("title_ar", sa.String(length=160), nullable=False),
        sa.Column("title_en", sa.String(length=160), nullable=False),
        sa.Column("description_ar", sa.String(length=400), nullable=True),
        sa.Column("description_en", sa.String(length=400), nullable=True),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("widget_type", sa.String(length=16), nullable=False),
        sa.Column("data_source", sa.String(length=200), nullable=True),
        sa.Column("default_span", sa.Integer(), nullable=False),
        sa.Column("min_span", sa.Integer(), nullable=False),
        sa.Column("max_span", sa.Integer(), nullable=False),
        sa.Column("required_perms", sa.JSON(), nullable=False),
        sa.Column("config_schema", sa.JSON(), nullable=True),
        sa.Column("refresh_secs", sa.Integer(), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "code", name="uq_dashboard_widget_code"),
    )
    op.create_index(
        op.f("ix_dashboard_widgets_code"),
        "dashboard_widgets",
        ["code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dashboard_widgets_tenant_id"),
        "dashboard_widgets",
        ["tenant_id"],
        unique=False,
    )

    # Layout
    op.create_table(
        "dashboard_layouts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=True),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("owner_id", sa.String(length=120), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("blocks", sa.JSON(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "scope",
            "owner_id",
            "name",
            name="uq_dashboard_layout_scope",
        ),
    )
    op.create_index(
        "ix_dashboard_layouts_owner",
        "dashboard_layouts",
        ["scope", "owner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dashboard_layouts_owner_id"),
        "dashboard_layouts",
        ["owner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dashboard_layouts_tenant_id"),
        "dashboard_layouts",
        ["tenant_id"],
        unique=False,
    )

    # Snapshot cache
    op.create_table(
        "dashboard_data_cache",
        sa.Column("cache_key", sa.String(length=256), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("cache_key"),
    )
    op.create_index(
        "ix_dashboard_cache_expiry",
        "dashboard_data_cache",
        ["expires_at"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index("ix_dashboard_cache_expiry", table_name="dashboard_data_cache")
    op.drop_table("dashboard_data_cache")

    op.drop_index(
        op.f("ix_dashboard_layouts_tenant_id"), table_name="dashboard_layouts"
    )
    op.drop_index(op.f("ix_dashboard_layouts_owner_id"), table_name="dashboard_layouts")
    op.drop_index("ix_dashboard_layouts_owner", table_name="dashboard_layouts")
    op.drop_table("dashboard_layouts")

    op.drop_index(op.f("ix_dashboard_widgets_tenant_id"), table_name="dashboard_widgets")
    op.drop_index(op.f("ix_dashboard_widgets_code"), table_name="dashboard_widgets")
    op.drop_table("dashboard_widgets")
