/// APEX Commands Registry — single source of truth for Cmd+K palette.
///
/// Call [buildAppCommands] to get the full list of app-level commands
/// (navigation + actions). Feature-level commands can be merged in at
/// the feature boundary by calling [buildAppCommands] + adding their own.
library;

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

import 'apex_ask_panel.dart';
import 'apex_command_palette.dart';

/// Builds the list of commands available everywhere in the app.
List<ApexCommand> buildAppCommands(BuildContext context) {
  void go(String path) => GoRouter.of(context).go(path);

  return [
    // ── Ask APEX (top of list — the highest-leverage AI surface) ──
    ApexCommand.action(
      id: 'ask_apex',
      label: 'اسأل أبكس',
      subtitle: 'سؤال طبيعي للمساعد الذكي حول دفاترك',
      icon: Icons.auto_awesome,
      shortcut: 'CTRL /',
      onRun: (ctx) => openApexAskPanel(ctx),
    ),
    // ── New IA primary destinations (blueprint v1.0) ──
    ApexCommand(
      id: 'nav_today',
      label: 'اليوم — لوحة المؤشرات',
      subtitle: 'النقد + الذمم + AI Pulse + فاتورة سريعة',
      kind: ApexCommandKind.navigation,
      icon: Icons.dashboard_outlined,
      shortcut: 'G T',
      onRun: (_) => go('/today'),
    ),
    ApexCommand(
      id: 'nav_sales',
      label: 'المبيعات — دورة كاملة',
      subtitle: 'العملاء + الفواتير + الإصدار + الترحيل',
      kind: ApexCommandKind.navigation,
      icon: Icons.receipt_long_outlined,
      shortcut: 'G S',
      onRun: (_) => go('/sales'),
    ),
    ApexCommand(
      id: 'nav_purchase',
      label: 'المشتريات',
      subtitle: 'الموردون + فواتير الشراء',
      kind: ApexCommandKind.navigation,
      icon: Icons.shopping_cart_outlined,
      shortcut: 'G P',
      onRun: (_) => go('/purchase'),
    ),
    ApexCommand(
      id: 'nav_accounting_tb',
      label: 'ميزان المراجعة (Live)',
      subtitle: 'TB + قائمة الدخل + الميزانية مع drill-down',
      kind: ApexCommandKind.navigation,
      icon: Icons.assessment_outlined,
      shortcut: 'G B',
      onRun: (_) => go('/accounting/trial-balance'),
    ),
    ApexCommand(
      id: 'nav_audit',
      label: 'مساحة عمل المراجعة',
      subtitle: 'Workpapers + PBC + Sampling + Benford + Sign-off',
      kind: ApexCommandKind.navigation,
      icon: Icons.verified_user_outlined,
      shortcut: 'G A',
      onRun: (_) => go('/audit'),
    ),
    ApexCommand(
      id: 'action_receipt_capture',
      label: 'التقط إيصالاً',
      subtitle: 'OCR للإيصالات وتحويلها إلى مصروف',
      kind: ApexCommandKind.action,
      icon: Icons.receipt,
      shortcut: 'C R',
      onRun: (_) => go('/receipt/capture'),
    ),
    ApexCommand(
      id: 'action_period_close',
      label: 'إقفال الفترة',
      subtitle: 'NetSuite-style checklist',
      kind: ApexCommandKind.action,
      icon: Icons.lock_clock_outlined,
      onRun: (_) => go('/operations/period-close'),
    ),
    ApexCommand(
      id: 'nav_customers',
      label: 'قائمة العملاء',
      subtitle: 'كل العملاء مع فلاتر',
      kind: ApexCommandKind.navigation,
      icon: Icons.people_outline,
      onRun: (_) => go('/sales/customers'),
    ),
    ApexCommand(
      id: 'nav_vendors',
      label: 'قائمة الموردين',
      subtitle: 'كل الموردين',
      kind: ApexCommandKind.navigation,
      icon: Icons.local_shipping_outlined,
      onRun: (_) => go('/purchase/vendors'),
    ),
    ApexCommand(
      id: 'nav_invoices',
      label: 'قائمة الفواتير',
      subtitle: 'مسودة / صادرة / متأخرة / مدفوعة',
      kind: ApexCommandKind.navigation,
      icon: Icons.receipt_long_outlined,
      onRun: (_) => go('/sales/invoices'),
    ),
    ApexCommand(
      id: 'nav_ar_aging',
      label: 'أعمار الذمم',
      subtitle: 'AR Aging buckets — current / 30 / 60 / 90+',
      kind: ApexCommandKind.navigation,
      icon: Icons.timeline_outlined,
      onRun: (_) => go('/sales/aging'),
    ),
    ApexCommand(
      id: 'nav_settings',
      label: 'الإعدادات',
      subtitle: 'الحساب / الكيان / التكاملات / الإشعارات',
      kind: ApexCommandKind.navigation,
      icon: Icons.settings_outlined,
      shortcut: 'CTRL ,',
      onRun: (_) => go('/settings/unified'),
    ),
    ApexCommand(
      id: 'nav_bills',
      label: 'فواتير الموردين',
      subtitle: 'مسودة / مرحلة / متأخرة / مدفوعة',
      kind: ApexCommandKind.navigation,
      icon: Icons.receipt_outlined,
      onRun: (_) => go('/purchase/bills'),
    ),
    ApexCommand(
      id: 'nav_ap_aging',
      label: 'أعمار ذمم الموردين',
      subtitle: 'AP Aging buckets',
      kind: ApexCommandKind.navigation,
      icon: Icons.timeline,
      onRun: (_) => go('/purchase/aging'),
    ),
    ApexCommand(
      id: 'nav_je_list_v2',
      label: 'القيود اليومية (canonical)',
      subtitle: 'كل القيود مع filters: مرحّل / مسودة / معكوس',
      kind: ApexCommandKind.navigation,
      icon: Icons.book_outlined,
      onRun: (_) => go('/accounting/je-list'),
    ),
    ApexCommand(
      id: 'nav_coa_v2',
      label: 'شجرة الحسابات (SOCPA)',
      subtitle: '38+ حساب — drill إلى Account Ledger',
      kind: ApexCommandKind.navigation,
      icon: Icons.account_tree_outlined,
      onRun: (_) => go('/accounting/coa-v2'),
    ),
    ApexCommand(
      id: 'nav_hr_employees',
      label: 'الموظفون + Saudization',
      subtitle: 'قائمة الموظفين مع نسبة السعودة',
      kind: ApexCommandKind.navigation,
      icon: Icons.people_outline,
      onRun: (_) => go('/hr/employees'),
    ),
    ApexCommand(
      id: 'nav_tax_calendar_v2',
      label: 'التقويم الضريبي السعودي',
      subtitle: 'VAT + زكاة + GOSI + ZATCA + سعودة',
      kind: ApexCommandKind.navigation,
      icon: Icons.event_outlined,
      onRun: (_) => go('/compliance/tax-calendar'),
    ),
    ApexCommand(
      id: 'nav_cashflow_forecast',
      label: 'توقع التدفق النقدي',
      subtitle: 'إسقاط 90 يوماً + شهور التشغيل + سيناريوهات AI',
      kind: ApexCommandKind.navigation,
      icon: Icons.show_chart,
      onRun: (_) => go('/analytics/cash-flow-forecast'),
    ),
    ApexCommand(
      id: 'action_pos_quick_sale',
      label: 'بيع سريع — POS',
      subtitle: 'كاش/مدى/STC Pay/Apple Pay',
      kind: ApexCommandKind.action,
      icon: Icons.point_of_sale,
      shortcut: 'C P',
      onRun: (_) => go('/pos/quick-sale'),
    ),
    ApexCommand(
      id: 'nav_notifications',
      label: 'الإشعارات',
      subtitle: 'صندوق الوارد + الإشعارات',
      kind: ApexCommandKind.navigation,
      icon: Icons.notifications_outlined,
      onRun: (_) => go('/notifications/panel'),
    ),
    ApexCommand(
      id: 'nav_ai_console',
      label: 'مركز الذكاء الاصطناعي',
      subtitle: 'الاستهلاك والنشاط الأخير واختصارات الاعتماد',
      kind: ApexCommandKind.navigation,
      icon: Icons.hub_outlined,
      onRun: (_) => go('/admin/ai-console'),
    ),
    ApexCommand(
      id: 'nav_ai_inbox',
      label: 'صندوق اقتراحات الذكاء الاصطناعي',
      subtitle: 'مراجعة والموافقة على ما يقترحه الـ Copilot',
      kind: ApexCommandKind.navigation,
      icon: Icons.inbox_outlined,
      onRun: (_) => go('/admin/ai-suggestions'),
    ),
    ApexCommand(
      id: 'nav_tax_timeline',
      label: 'التقويم الضريبي',
      subtitle: 'الاستحقاقات القادمة (VAT / زكاة / ضريبة الشركات / ZATCA)',
      kind: ApexCommandKind.navigation,
      icon: Icons.event_note_outlined,
      onRun: (_) => go('/compliance/tax-timeline'),
    ),
    ApexCommand(
      id: 'nav_bank_rec_ai',
      label: 'التسوية البنكية بالذكاء الاصطناعي',
      subtitle: 'مطابقة حركات البنك بقيود اليومية تلقائياً',
      kind: ApexCommandKind.navigation,
      icon: Icons.compare_arrows,
      onRun: (_) => go('/compliance/bank-rec-ai'),
    ),
    ApexCommand(
      id: 'nav_audit_workflow',
      label: 'ورشة المراجعة (Benford / عينة قيود / أوراق عمل)',
      subtitle: 'أدوات مراجعة SOX / ISA 240 / IFRS 15',
      kind: ApexCommandKind.navigation,
      icon: Icons.fact_check_outlined,
      onRun: (_) => go('/compliance/audit-workflow-ai'),
    ),
    ApexCommand(
      id: 'nav_islamic_finance',
      label: 'المنتجات الإسلامية (مرابحة / إجارة / زكاة)',
      subtitle: 'AAOIFI-aligned — FAS 28 / 32',
      kind: ApexCommandKind.navigation,
      icon: Icons.mosque_outlined,
      onRun: (_) => go('/compliance/islamic-finance'),
    ),
    ApexCommand(
      id: 'nav_depreciation_ai',
      label: 'جدول إهلاك الأصول (IAS 16)',
      subtitle: 'خط مستقيم · رصيد متناقص · Double-Declining',
      kind: ApexCommandKind.navigation,
      icon: Icons.trending_down,
      onRun: (_) => go('/compliance/depreciation-ai'),
    ),
    ApexCommand(
      id: 'nav_multi_currency',
      label: 'لوحة العملات المتعددة',
      subtitle: 'مراكز بالعملة الأصلية + التعرّض للصرف الأجنبي',
      kind: ApexCommandKind.navigation,
      icon: Icons.currency_exchange,
      onRun: (_) => go('/compliance/multi-currency'),
    ),
    ApexCommand(
      id: 'nav_onboarding',
      label: 'معالج تهيئة الحساب',
      subtitle: 'إعداد الشركة + قالب COA صناعي',
      kind: ApexCommandKind.navigation,
      icon: Icons.rocket_launch_outlined,
      onRun: (_) => go('/onboarding/wizard'),
    ),
    ApexCommand(
      id: 'nav_audit_chain',
      label: 'سجل التدقيق — السلسلة المشفّرة',
      subtitle: 'Tamper-evident SHA-256 chain verifier',
      kind: ApexCommandKind.navigation,
      icon: Icons.link,
      onRun: (_) => go('/admin/audit-chain'),
    ),
    ApexCommand(
      id: 'nav_ops_hub',
      label: 'مركز العمليات المالية',
      subtitle: 'عملاء · موردين · أصناف · قيود · فواتير · ميزان مراجعة',
      kind: ApexCommandKind.navigation,
      icon: Icons.business_center,
      onRun: (_) => go('/financial-ops'),
    ),
    ApexCommand(
      id: 'nav_je_builder',
      label: 'إنشاء قيد يومية',
      subtitle: 'منشئ القيود مع القوالب + ترقيم ZATCA',
      kind: ApexCommandKind.navigation,
      icon: Icons.edit_note,
      onRun: (_) => go('/compliance/journal-entry-builder'),
    ),
    ApexCommand(
      id: 'nav_je_list',
      label: 'قيود اليومية — القائمة',
      subtitle: 'عرض / مراجعة / فحص توازن',
      kind: ApexCommandKind.navigation,
      icon: Icons.list_alt,
      onRun: (_) => go('/compliance/journal-entries'),
    ),
    ApexCommand(
      id: 'nav_fs',
      label: 'القوائم المالية',
      subtitle: 'ميزان · قائمة الدخل · قائمة المركز · قيود الإقفال',
      kind: ApexCommandKind.navigation,
      icon: Icons.assessment_outlined,
      onRun: (_) => go('/compliance/financial-statements'),
    ),
    ApexCommand(
      id: 'nav_ratios',
      label: 'النسب المالية',
      subtitle: 'السيولة · الرافعة · الربحية · الكفاءة',
      kind: ApexCommandKind.navigation,
      icon: Icons.insights,
      onRun: (_) => go('/compliance/ratios'),
    ),
    ApexCommand(
      id: 'nav_universal_journal',
      label: 'السجل الموحّد (SAP ACDOCA + Odoo multi-view)',
      subtitle: 'كل الحركات المالية · List / Kanban / Pivot · دفاتر متوازية',
      kind: ApexCommandKind.navigation,
      icon: Icons.hub,
      onRun: (_) => go('/operations/universal-journal'),
    ),
    ApexCommand(
      id: 'nav_period_close',
      label: 'إقفال الفترة المحاسبية (NetSuite-pattern)',
      subtitle: '12 مهمة متسلسلة + تبعيات + توقيع اعتماد',
      kind: ApexCommandKind.navigation,
      icon: Icons.lock_clock,
      onRun: (_) => go('/operations/period-close'),
    ),
    ApexCommand(
      id: 'nav_pos_sessions',
      label: 'جلسات نقاط البيع',
      subtitle: 'فتح / قفل / Z-report',
      kind: ApexCommandKind.navigation,
      icon: Icons.point_of_sale,
      onRun: (_) => go('/operations/pos-sessions'),
    ),
    ApexCommand(
      id: 'nav_purchase_cycle',
      label: 'دورة المشتريات الكاملة',
      subtitle: 'PO → GRN → PI → سند صرف',
      kind: ApexCommandKind.navigation,
      icon: Icons.shopping_cart,
      onRun: (_) => go('/operations/purchase-cycle'),
    ),
    ApexCommand(
      id: 'nav_consolidation_ui',
      label: 'توحيد الكيانات — Consolidation',
      subtitle: 'موازين متعدّدة الكيانات → ميزان موحّد',
      kind: ApexCommandKind.navigation,
      icon: Icons.account_tree,
      onRun: (_) => go('/operations/consolidation-ui'),
    ),

    // ── Navigation ──
    ApexCommand.navigation(
      id: 'nav_home',
      label: 'الرئيسية',
      path: '/home',
      icon: Icons.home_outlined,
      shortcut: 'G H',
    ),
    ApexCommand(
      id: 'nav_dashboard',
      label: 'لوحة التحكم التنفيذية',
      kind: ApexCommandKind.navigation,
      icon: Icons.dashboard_outlined,
      onRun: (_) => go('/compliance/executive-dashboard'),
    ),
    ApexCommand(
      id: 'nav_compliance',
      label: 'الامتثال',
      kind: ApexCommandKind.navigation,
      icon: Icons.shield_outlined,
      onRun: (_) => go('/compliance'),
    ),
    ApexCommand(
      id: 'nav_journal_entries',
      label: 'قيود اليومية',
      kind: ApexCommandKind.navigation,
      icon: Icons.receipt_long_outlined,
      onRun: (_) => go('/compliance/journal-entries'),
    ),
    ApexCommand(
      id: 'nav_zatca',
      label: 'فاتورة ZATCA',
      subtitle: 'إنشاء فاتورة إلكترونية متوافقة مع هيئة الزكاة',
      kind: ApexCommandKind.navigation,
      icon: Icons.qr_code_2,
      onRun: (_) => go('/compliance/zatca-invoice'),
    ),
    ApexCommand(
      id: 'nav_vat_return',
      label: 'إقرار ضريبة القيمة المضافة',
      kind: ApexCommandKind.navigation,
      icon: Icons.description_outlined,
      onRun: (_) => go('/compliance/vat-return'),
    ),
    ApexCommand(
      id: 'nav_zakat',
      label: 'حاسبة الزكاة',
      kind: ApexCommandKind.navigation,
      icon: Icons.calculate_outlined,
      onRun: (_) => go('/compliance/zakat'),
    ),
    ApexCommand(
      id: 'nav_bank_rec',
      label: 'المطابقة البنكية',
      kind: ApexCommandKind.navigation,
      icon: Icons.compare_arrows,
      onRun: (_) => go('/compliance/bank-rec'),
    ),
    ApexCommand(
      id: 'nav_payroll',
      label: 'الرواتب',
      kind: ApexCommandKind.navigation,
      icon: Icons.badge_outlined,
      onRun: (_) => go('/compliance/payroll'),
    ),
    ApexCommand(
      id: 'nav_ratios',
      label: 'النسب المالية',
      kind: ApexCommandKind.navigation,
      icon: Icons.bar_chart,
      onRun: (_) => go('/compliance/ratios'),
    ),
    ApexCommand(
      id: 'nav_fixed_assets',
      label: 'الأصول الثابتة',
      kind: ApexCommandKind.navigation,
      icon: Icons.business_outlined,
      onRun: (_) => go('/compliance/depreciation'),
    ),
    ApexCommand(
      id: 'nav_cashflow',
      label: 'التدفق النقدي',
      kind: ApexCommandKind.navigation,
      icon: Icons.waterfall_chart,
      onRun: (_) => go('/compliance/cashflow'),
    ),
    ApexCommand(
      id: 'nav_breakeven',
      label: 'نقطة التعادل',
      kind: ApexCommandKind.navigation,
      icon: Icons.trending_up,
      onRun: (_) => go('/compliance/breakeven'),
    ),

    // ── What's New (featured first) ──
    ApexCommand(
      id: 'nav_whats_new',
      label: '🚀 ما الجديد في APEX',
      subtitle: '50+ ميزة جديدة — Hub كامل',
      kind: ApexCommandKind.navigation,
      icon: Icons.rocket_launch,
      onRun: (ctx) => GoRouter.of(ctx).go('/whats-new'),
    ),
    ApexCommand(
      id: 'nav_apex_showcase',
      label: 'معرض مكوّنات APEX',
      subtitle: 'شاهد كل المكوّنات الجديدة في مكان واحد (Sprint 35)',
      kind: ApexCommandKind.navigation,
      icon: Icons.auto_awesome_outlined,
      onRun: (ctx) => GoRouter.of(ctx).go('/showcase'),
    ),
    // ── Interactive demos of each new backend feature ──
    ApexCommand(
      id: 'nav_uae_corp_tax',
      label: 'حاسبة ضريبة الشركات UAE',
      subtitle: '9% + 375K exempt + SBR + QFZP',
      kind: ApexCommandKind.navigation,
      icon: Icons.account_balance,
      onRun: (ctx) => GoRouter.of(ctx).go('/uae-corp-tax'),
    ),
    ApexCommand(
      id: 'nav_startup_metrics',
      label: 'Startup Metrics Live',
      subtitle: 'Burn / Runway / MRR / LTV / Rule of 40',
      kind: ApexCommandKind.navigation,
      icon: Icons.trending_up,
      onRun: (ctx) => GoRouter.of(ctx).go('/startup-metrics'),
    ),
    ApexCommand(
      id: 'nav_industry_packs',
      label: 'حزم الصناعات',
      subtitle: 'F&B / مقاولات / عيادات / لوجستيك / خدمات',
      kind: ApexCommandKind.navigation,
      icon: Icons.apps,
      onRun: (ctx) => GoRouter.of(ctx).go('/industry-packs'),
    ),
    ApexCommand(
      id: 'nav_payments_playground',
      label: 'Payments Playground',
      subtitle: 'Mada / STC Pay / Apple Pay / Tabby',
      kind: ApexCommandKind.navigation,
      icon: Icons.payment,
      onRun: (ctx) => GoRouter.of(ctx).go('/payments-playground'),
    ),
    ApexCommand(
      id: 'nav_ap_pipeline',
      label: 'AP Agent Pipeline',
      subtitle: 'محاكاة تدفق اعتماد الفواتير الذاتي',
      kind: ApexCommandKind.navigation,
      icon: Icons.smart_toy_outlined,
      onRun: (ctx) => GoRouter.of(ctx).go('/ap-pipeline-demo'),
    ),
    ApexCommand(
      id: 'nav_bank_ocr',
      label: 'Bank OCR Demo',
      subtitle: 'تحليل كشوف بنكية CSV بالعربية',
      kind: ApexCommandKind.navigation,
      icon: Icons.compare_arrows,
      onRun: (ctx) => GoRouter.of(ctx).go('/bank-ocr-demo'),
    ),
    ApexCommand(
      id: 'nav_gosi_demo',
      label: 'حاسبة GOSI / GPSSA',
      subtitle: 'KSA 10/12% | UAE 5/12.5%',
      kind: ApexCommandKind.navigation,
      icon: Icons.calculate,
      onRun: (ctx) => GoRouter.of(ctx).go('/gosi-demo'),
    ),
    ApexCommand(
      id: 'nav_eosb_demo',
      label: 'مكافأة نهاية الخدمة EOSB',
      subtitle: 'KSA Art. 84-85 + UAE Art. 51-52',
      kind: ApexCommandKind.navigation,
      icon: Icons.logout,
      onRun: (ctx) => GoRouter.of(ctx).go('/eosb-demo'),
    ),
    ApexCommand(
      id: 'nav_whatsapp_demo',
      label: 'قوالب WhatsApp',
      subtitle: '7 قوالب عربية معتمدة',
      kind: ApexCommandKind.navigation,
      icon: Icons.chat_bubble_outline,
      onRun: (ctx) => GoRouter.of(ctx).go('/whatsapp-demo'),
    ),
    ApexCommand(
      id: 'nav_onboarding',
      label: 'معالج الإعداد (Onboarding)',
      subtitle: '5 خطوات لإعداد شركتك في أقل من 5 دقائق',
      kind: ApexCommandKind.navigation,
      icon: Icons.rocket_launch,
      onRun: (ctx) => GoRouter.of(ctx).go('/onboarding'),
    ),

    // ── Actions ──
    ApexCommand.action(
      id: 'action_new_journal_entry',
      label: 'قيد يومية جديد',
      subtitle: 'إنشاء قيد بالدائن والمدين',
      icon: Icons.add_box_outlined,
      shortcut: 'N J',
      onRun: (ctx) => GoRouter.of(ctx).go('/compliance/journal-entries/new'),
    ),
    ApexCommand.action(
      id: 'action_new_zatca_invoice',
      label: 'فاتورة ZATCA جديدة',
      icon: Icons.add_to_photos,
      shortcut: 'N I',
      onRun: (ctx) => GoRouter.of(ctx).go('/compliance/zatca-invoice'),
    ),
    ApexCommand.action(
      id: 'action_upload_coa',
      label: 'رفع دليل الحسابات',
      icon: Icons.upload_file,
      onRun: (ctx) => GoRouter.of(ctx).go('/coa/upload'),
    ),
    ApexCommand.action(
      id: 'action_open_copilot',
      label: 'المساعد الذكي',
      subtitle: 'اسأل Copilot بالعربية أو الإنجليزية',
      icon: Icons.auto_awesome,
      onRun: (ctx) => GoRouter.of(ctx).go('/copilot'),
    ),
    ApexCommand.action(
      id: 'action_knowledge_brain',
      label: 'قاعدة المعرفة',
      icon: Icons.psychology_outlined,
      onRun: (ctx) => GoRouter.of(ctx).go('/knowledge'),
    ),
    ApexCommand.action(
      id: 'action_settings',
      label: 'الإعدادات',
      icon: Icons.settings_outlined,
      onRun: (ctx) => GoRouter.of(ctx).go('/settings'),
    ),
    ApexCommand.action(
      id: 'action_marketplace',
      label: 'سوق الخدمات',
      icon: Icons.storefront_outlined,
      onRun: (ctx) => GoRouter.of(ctx).go('/marketplace'),
    ),
  ];
}
