"""ERR-2 Phase 3 — Audit deliverable for the future G-RLS-MIGRATION PR.

Walks every Python file under `app/` looking for `__tablename__`
declarations whose surrounding window mentions either `tenant_id` or
`TenantMixin` (the two ways a model is tenant-scoped in this codebase).

Emits a markdown table to stdout. The output is what
`docs/TENANT_TABLES_AUDIT_2026-05-07.md` is generated from — kept as a
script so the list can be re-generated later when new tenant-scoped
models land. Idempotent.

Usage:
    python scripts/dev/audit_tenant_tables.py > docs/TENANT_TABLES_AUDIT_<date>.md
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
APP = REPO / "app"

TABLE_RE = re.compile(
    r"__tablename__\s*=\s*[\"']([a-z_][a-z0-9_]+)[\"']"
)


def find_tables() -> list[tuple[str, str, int, bool]]:
    """Return `(table, file, line, uses_TenantMixin)` per tenant-scoped table."""
    hits: list[tuple[str, str, int, bool]] = []
    for root, _, files in os.walk(APP):
        for f in files:
            if not f.endswith(".py"):
                continue
            path = Path(root) / f
            try:
                txt = path.read_text(encoding="utf-8")
            except Exception:
                continue
            for m in TABLE_RE.finditer(txt):
                tname = m.group(1)
                idx = m.start()
                snippet = txt[max(0, idx - 2000) : idx + 1500]
                if "tenant_id" not in snippet and "TenantMixin" not in snippet:
                    continue
                line = txt[:idx].count("\n") + 1
                has_mixin = "TenantMixin" in snippet
                rel = path.relative_to(REPO).as_posix()
                hits.append((tname, rel, line, has_mixin))

    # Dedupe by tablename — keep first occurrence (canonical model file).
    seen: set[str] = set()
    unique: list[tuple[str, str, int, bool]] = []
    for h in hits:
        if h[0] in seen:
            continue
        seen.add(h[0])
        unique.append(h)
    unique.sort()
    return unique


def main() -> None:
    rows = find_tables()
    print("# Tenant-Scoped Tables Audit (2026-05-07)")
    print()
    print(
        "**Purpose.** Input artifact for the future `G-RLS-MIGRATION` PR. "
        "Lists every model whose `__tablename__` declaration sits within "
        "~2 KB of a `tenant_id` column or a `TenantMixin` reference."
    )
    print()
    print(
        "**Scope of the PR that ships this file (ERR-2 Phase 3).** *Not* "
        "enabling RLS on these tables. Only fixing the actual cross-tenant "
        "leak documented in UAT Issue #3 — which was a missing tenant row "
        "at registration + a missing `tenant_id` JWT claim, *not* a missing "
        "DB-layer RLS enforcement. The app-layer tenant guard "
        "(`TenantContextMiddleware` + `attach_tenant_guard()`) was already "
        "wired before this PR and works correctly once the JWT carries a "
        "tenant id."
    )
    print()
    print(
        "**Why the audit lives here.** The future G-RLS-MIGRATION PR will "
        "need a definitive list of tables that should have a "
        "`CREATE POLICY tenant_isolation` attached. Producing that list "
        "now — while the model code is fresh — saves the next PR from "
        "having to redo this scan and risk missing a table."
    )
    print()
    print(f"**Total unique tenant-scoped tables found:** {len(rows)}.")
    print()
    print("Generated by `scripts/dev/audit_tenant_tables.py`.")
    print()
    print("| # | Table | Source | Mixin? |")
    print("|---|-------|--------|--------|")
    for i, (tname, path, line, mixin) in enumerate(rows, 1):
        marker = "TenantMixin" if mixin else "tenant_id col"
        print(f"| {i} | `{tname}` | `{path}:{line}` | {marker} |")
    print()
    print("## Recommended G-RLS-MIGRATION rollout")
    print()
    print(
        "Per `CLAUDE.md` G-A3.1 (the prior production incident from a "
        "bulk auto-generated migration), enabling RLS on every table at "
        "once is exactly the wrong shape of change."
    )
    print()
    print("1. **Pilot wave** — one low-traffic table (e.g. `pilot_branches`).")
    print("   Apply RLS in a hand-written, idempotent migration with explicit")
    print("   `IF NOT EXISTS` guards. Verify in staging for ~1 week.")
    print(
        "2. **Critical financial wave** — invoices, journal entries, GL "
        "(~10 tables). Separate PR, separate staging window."
    )
    print("3. **Master-data wave** — customers, vendors, products (~20 tables).")
    print(
        "4. **Operational wave** — the remaining ~140 tables in "
        "logical batches of 20-30."
    )
    print()
    print("Each wave: one migration, one PR, staging verification, gradual")
    print(
        "rollout via a `RLS_ENFORCE_<wave>` env flag. Defense-in-depth on "
        "top of the app-layer guard — never the only line of defense."
    )
    print()
    print("## Prerequisite")
    print()
    print(
        "Tickets `G-CI-DOCKER-POSTGRES` (testcontainers-postgres in CI) "
        "and `G-LEGACY-TENANT-MIGRATION` (backfill script for users still "
        "on the shared `06892550-…` tenant) must land before G-RLS-MIGRATION."
    )


if __name__ == "__main__":
    sys.exit(main() or 0)
